/* eslint-disable @next/next/no-html-link-for-pages */
"use client";import{useEffect,useMemo,useState}from"react";import*as XLSX from"xlsx";
type Supplier={id:number;name:string;active:number};type Product={id:number;supplierId:number;article:string;name:string;weight:number|null;price:number;vegan:number;hit:number;active:number};
export default function AdminClient(){const[suppliers,setSuppliers]=useState<Supplier[]>([]);const[products,setProducts]=useState<Product[]>([]);const[sid,setSid]=useState<number|null>(null);const[newSupplier,setNewSupplier]=useState("");const[notice,setNotice]=useState("");const[manual,setManual]=useState({article:"",name:"",weight:"",price:""});
async function load(){const r=await fetch("/api/admin");if(r.status===403){location.href="/login";return;}const d=await r.json();setSuppliers(d.suppliers);setProducts(d.products);setSid(s=>s??d.suppliers[0]?.id??null);}useEffect(()=>{// eslint-disable-next-line react-hooks/set-state-in-effect
void load()},[]);const list=useMemo(()=>products.filter(p=>p.supplierId===sid),[products,sid]);
async function post(body:unknown){const r=await fetch("/api/admin",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw new Error(d.error);return d;}
async function addSupplier(){if(!newSupplier.trim())return;await post({action:"supplier",name:newSupplier});setNewSupplier("");await load();}
async function save(p:Product){await post({action:"product",product:{...p,vegan:!!p.vegan,hit:!!p.hit,active:!!p.active}});setNotice("Изменения сохранены");await load();}
async function addManual(){if(!sid||!manual.name||!manual.price)return;await post({action:"manual",product:{supplierId:sid,...manual,weight:manual.weight?Number(manual.weight):null,price:Number(manual.price)}});setManual({article:"",name:"",weight:"",price:""});await load();}
async function upload(file:File){if(!sid)return;const data=await file.arrayBuffer();const wb=XLSX.read(data);const rows=XLSX.utils.sheet_to_json<unknown[]>(wb.Sheets[wb.SheetNames[0]],{header:1,defval:null});const h=rows.findIndex(r=>Array.isArray(r)&&r.some(v=>String(v||"").trim().toLowerCase()==="название"));if(h<0){setNotice("Не найдена колонка «Название»");return;}const headers=(rows[h]as unknown[]).map(v=>String(v||"").trim().toLowerCase());const col=(...names:string[])=>headers.findIndex(x=>names.includes(x));const ni=col("название"),ai=col("артикул"),pi=col("цена, р.","цена","цена, ₽"),wi=col("граммовка","граммовка, г","вес");const parsed=(rows.slice(h+1)as unknown[][]).filter(r=>r[ni]&&r[pi]!=null).map(r=>{let name=String(r[ni]).replace(/\s+/g," ").trim();let weight=wi>=0&&r[wi]!=null?Number(String(r[wi]).match(/\d+/)?.[0]):null;const m=name.match(/\s+(\d+)\s*(?:г|гр)\s*_[\p{L}\p{N}-]{2,16}$/iu);if(m){weight=weight||Number(m[1]);name=name.slice(0,m.index).trim();}return{article:ai>=0?String(r[ai]||""):"",name:name.toUpperCase(),weight,price:Number(r[pi])};});const result=await post({action:"import",supplierId:sid,rows:parsed});setNotice(`Загружено позиций: ${result.imported}`);await load();}
return <main className="admin-shell"><header className="admin-header"><a href="/" className="admin-logo">ONE <span>PRICE</span></a><div><h1>Управление каталогом</h1><p>Поставщики, позиции, цены и фишки</p></div><a href="/">Панель партнёра →</a></header><section className="admin-grid"><aside className="admin-suppliers"><h2>Поставщики</h2>{suppliers.map(s=><button key={s.id} className={sid===s.id?"active":""} onClick={()=>setSid(s.id)}>{s.name}<span>{products.filter(p=>p.supplierId===s.id).length}</span></button>)}<div className="add-supplier"><input placeholder="Новый поставщик" value={newSupplier} onChange={e=>setNewSupplier(e.target.value)}/><button onClick={addSupplier}>Добавить</button></div></aside><section className="admin-content"><div className="admin-actions"><div><h2>{suppliers.find(s=>s.id===sid)?.name||"Выберите поставщика"}</h2><p>{list.length} позиций</p></div><label className="upload-button">Загрузить Excel<input type="file" accept=".xlsx,.xls" onChange={e=>e.target.files?.[0]&&upload(e.target.files[0])}/></label></div>{notice&&<p className="notice">{notice}</p>}<div className="manual-form"><input placeholder="Артикул" value={manual.article} onChange={e=>setManual({...manual,article:e.target.value})}/><input className="wide" placeholder="Название позиции" value={manual.name} onChange={e=>setManual({...manual,name:e.target.value})}/><input placeholder="Граммы" value={manual.weight} onChange={e=>setManual({...manual,weight:e.target.value})}/><input placeholder="Цена" value={manual.price} onChange={e=>setManual({...manual,price:e.target.value})}/><button onClick={addManual}>Добавить вручную</button></div><div className="admin-table"><div className="admin-row head"><span>Название</span><span>Г</span><span>Цена</span><span>Веган</span><span>Хит</span><span>Активна</span><span/></div>{list.map(p=><div className="admin-row" key={p.id}><input value={p.name} onChange={e=>setProducts(cur=>cur.map(x=>x.id===p.id?{...x,name:e.target.value}:x))}/><input value={p.weight??""} onChange={e=>setProducts(cur=>cur.map(x=>x.id===p.id?{...x,weight:e.target.value?Number(e.target.value):null}:x))}/><input value={p.price} onChange={e=>setProducts(cur=>cur.map(x=>x.id===p.id?{...x,price:Number(e.target.value)}:x))}/><input type="checkbox" checked={!!p.vegan} onChange={e=>setProducts(cur=>cur.map(x=>x.id===p.id?{...x,vegan:e.target.checked?1:0}:x))}/><input type="checkbox" checked={!!p.hit} onChange={e=>setProducts(cur=>cur.map(x=>x.id===p.id?{...x,hit:e.target.checked?1:0}:x))}/><input type="checkbox" checked={!!p.active} onChange={e=>setProducts(cur=>cur.map(x=>x.id===p.id?{...x,active:e.target.checked?1:0}:x))}/><button onClick={()=>save(p)}>Сохранить</button></div>)}</div></section></section></main>}
