import { ensureDatabase,getD1 } from "../../../db/runtime"; import { sessionCookie,verifySession } from "../../auth";
async function allowed(request:Request){return(await verifySession(sessionCookie(request)))==="admin";}
export async function GET(request:Request){if(!await allowed(request))return Response.json({error:"Нет доступа"},{status:403});await ensureDatabase();const db=getD1();const suppliers=await db.prepare("SELECT id,name,active FROM suppliers ORDER BY name").all();const products=await db.prepare("SELECT id,supplier_id AS supplierId,article,name,weight,price,vegan,hit,active FROM products ORDER BY supplier_id,name").all();return Response.json({suppliers:suppliers.results,products:products.results});}
export async function POST(request:Request){if(!await allowed(request))return Response.json({error:"Нет доступа"},{status:403});await ensureDatabase();const db=getD1();const body=await request.json() as Record<string,unknown>;
 if(body.action==="supplier"){const name=String(body.name||"").trim();if(!name)return Response.json({error:"Укажите название поставщика"},{status:400});const supplier=await db.prepare("INSERT INTO suppliers(name) VALUES(?) ON CONFLICT(name) DO UPDATE SET active=1 RETURNING id,name").bind(name).first();return Response.json({supplier});}
 if(body.action==="product"){const p=body.product as Record<string,unknown>;await db.prepare("UPDATE products SET name=?,weight=?,price=?,vegan=?,hit=?,active=?,updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(String(p.name),p.weight==null?null:Number(p.weight),Number(p.price),p.vegan?1:0,p.hit?1:0,p.active===false?0:1,Number(p.id)).run();return Response.json({ok:true});}
 if(body.action==="manual"){const p=body.product as Record<string,unknown>;const article=String(p.article||`manual-${crypto.randomUUID()}`);await db.prepare("INSERT INTO products(supplier_id,article,name,weight,price,vegan,hit) VALUES(?,?,?,?,?,?,?) ON CONFLICT(supplier_id,article) DO UPDATE SET name=excluded.name,weight=excluded.weight,price=excluded.price,updated_at=CURRENT_TIMESTAMP").bind(Number(p.supplierId),article,String(p.name),p.weight==null?null:Number(p.weight),Number(p.price),p.vegan?1:0,p.hit?1:0).run();return Response.json({ok:true});}
 if(body.action==="import"){const supplierId=Number(body.supplierId);const rows=body.rows as Array<Record<string,unknown>>;const statements=rows.filter(r=>r.name&&r.price!=null).map(r=>db.prepare("INSERT INTO products(supplier_id,article,name,weight,price) VALUES(?,?,?,?,?) ON CONFLICT(supplier_id,article) DO UPDATE SET name=excluded.name,weight=excluded.weight,price=excluded.price,active=1,updated_at=CURRENT_TIMESTAMP").bind(supplierId,String(r.article||`name-${String(r.name).toLowerCase()}`),String(r.name),r.weight==null?null:Number(r.weight),Number(r.price)));for(let i=0;i<statements.length;i+=80)await db.batch(statements.slice(i,i+80));return Response.json({ok:true,imported:statements.length});}
 return Response.json({error:"Неизвестная операция"},{status:400});}
